gacs_workshop_summary.docx: gacs_workshop_summary.md
	pandoc -f markdown_github -t docx -o gacs_workshop_summary.docx gacs_workshop_summary.md

gacs_workshop_report.docx: gacs_workshop_report.md
	pandoc -f markdown_github -t docx -o gacs_workshop_report.docx gacs_workshop_report.md

